version: '2'
services:

  proxynuxeo:
    image: httpd:2.4
    volumes:
      - ./proxy/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./proxy/proxynuxeo.conf:/usr/local/apache2/conf/vhosts/proxynuxeo.conf
      - ./proxy/_default:/usr/local/apache2/conf/ssl/_default
    links:
      - nuxeo
    ports:
      - "80:80"
      - "443:443"

  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin4infra
    volumes:
      - data-postgres:/var/lib/postgres/data

  elasticsearch:
    image: elasticsearch
    volumes:
      - data-elasticsearch:/usr/share/elasticsearch/data

  nuxeo:
    # build:
    #   context: .
    #   dockerfile: Dockerfile-nuxeo
    image: arizona/nuxeo-ffmpeg
    ports:
      - "8080:8080"
    links:
      - postgres
    environment:
      NUXEO_DB_TYPE: postgresql
      NUXEO_DB_HOST: postgres
      NUXEO_DB_NAME: nuxeo
      NUXEO_DB_USER: nuxeo
      NUXEO_DB_PASSWORD: nuxeo

      NUXEO_PACKAGES: "nuxeo-diff nuxeo-spreadsheet nuxeo-dam nuxeo-template-rendering" # nuxeo-web-mobile nuxeo-drive  nuxeo-template-rendering-samples nuxeo-showcase-content

    volumes:
      - data-nuxeo:/var/lib/nuxeo/data

volumes:
  data-postgres:
    driver: local
  data-nuxeo:
    driver: local
  data-elasticsearch:
    driver: local
  data-redis:
    driver: local
