version: '2'
services:

  proxynuxeo:
    image: httpd:2.4
    volumes:
      - ./proxy/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./proxy/proxynuxeo.conf:/usr/local/apache2/conf/vhosts/proxynuxeo.conf
      - ./proxy/_default:/usr/local/apache2/conf/ssl/_default
    links:
      - nuxeo
    depends_on:
      - nuxeo
    ports:
      - "80:80"
      - "443:443"

  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin4infra
    volumes:
      - data-postgres:/var/lib/postgres/data

  elasticsearch:
    image: elasticsearch:1.5
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/conf/elasticsearch.yml
      - data-elasticsearch:/usr/share/elasticsearch/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - data-redis:/data

  nuxeo:
    # build:
    #   context: .
    #   dockerfile: Dockerfile-nuxeo
    image: arizona/nuxeo-ffmpeg
    ports:
      - "8080:8080"
    links:
      - redis
      - postgres
      - elasticsearch
    depends_on:
      - redis
      - postgres
      - elasticsearch
    environment:
      NUXEO_DB_TYPE: postgresql
      NUXEO_DB_HOST: postgres
      NUXEO_DB_NAME: nuxeo
      NUXEO_DB_USER: nuxeo
      NUXEO_DB_PASSWORD: nuxeo

      NUXEO_REDIS_HOST: redis
      NUXEO_REDIS_PORT: 6379

      NUXEO_ES_HOSTS: elasticsearch:9300
      NUXEO_ES_CLUSTER_NAME: elasticsearch
      NUXEO_ES_INDEX_NAME: nuxeo_tenant
      NUXEO_ES_REPLICAS: 0
      NUXEO_ES_SHARDS: 5

      NUXEO_PACKAGES: "nuxeo-diff nuxeo-spreadsheet nuxeo-dam nuxeo-template-rendering openid-authentication"
      # amazon-s3-online-storage - Requer registro no Nuxeo
      # nuxeo-web-mobile nuxeo-drive  nuxeo-template-rendering-samples nuxeo-showcase-content

    volumes:
      - data-nuxeo:/var/lib/nuxeo/data

  nuxeo_worker:
    # build:
    #   context: .
    #   dockerfile: Dockerfile-nuxeo
    image: arizona/nuxeo-ffmpeg
    environment:
      XXXXX: worker

  nuxeo_worker2:
    # build:
    #   context: .
    #   dockerfile: Dockerfile-nuxeo
    image: arizona/nuxeo-ffmpeg
    environment:
      XXXXX: worker

volumes:
  data-postgres:
    driver: local
  data-nuxeo:
    driver: local
  data-elasticsearch:
    driver: local
  data-redis:
    driver: local
