version: '2'
services:

  proxynuxeo:
    build: ./proxy
    links:
      - nuxeo
    depends_on:
      - nuxeo
    ports:
      - "80:80"
      - "443:443"

  postgres:
    build: ./postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin4infra
    volumes:
      - data-postgres:/var/lib/postgres/data

  elasticsearch:
    image: elasticsearch:1.5
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/conf/elasticsearch.yml
      - data-elasticsearch:/usr/share/elasticsearch/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - data-redis:/data

  nuxeo:
    build: ./nuxeo
    ports:
      - "8080:8080"
    links:
      - redis
      - postgres
      - elasticsearch
    depends_on:
      - redis
      - postgres
      - elasticsearch
    volumes:
      - data-nuxeo:/var/lib/nuxeo/data
    environment:
      NUXEO_DB_TYPE: postgresql
      NUXEO_DB_HOST: postgres
      NUXEO_DB_NAME: nuxeo
      NUXEO_DB_USER: nuxeo
      NUXEO_DB_PASSWORD: nuxeo

      NUXEO_REDIS_HOST: redis
      NUXEO_REDIS_PORT: 6379

      NUXEO_ES_HOSTS: elasticsearch:9300
      NUXEO_ES_CLUSTER_NAME: elasticsearch
      NUXEO_ES_INDEX_NAME: nuxeo_tenant
      NUXEO_ES_REPLICAS: 0
      NUXEO_ES_SHARDS: 5

      NUXEO_PACKAGES: "nuxeo-diff nuxeo-spreadsheet nuxeo-dam nuxeo-template-rendering openid-authentication" # nuxeo-web-mobile nuxeo-drive  nuxeo-template-rendering-samples nuxeo-showcase-content
      LOCAL_PACKAGES: "/tmp/packages/amazon-s3-online-storage-1.7.2.zip /tmp/packages/nuxeo-multi-tenant-1.6.2.zip" # /tmp/packages/nuxeo-extensions-package-1.1-SNAPSHOT.zip
      #### ATENCAO: amazon-s3-online-storage - Requer registro no Nuxeo

      NUXEO_S3_REGION: sa-east-1
      NUXEO_S3_BUCKET: teste-nuxeo
      NUXEO_S3_ID: AKIAI2MY6I73CJ2IEAEQ
      NUXEO_S3_SECRET: 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


volumes:
  data-postgres:
    driver: local
  data-nuxeo:
    driver: local
  data-elasticsearch:
    driver: local
  data-redis:
    driver: local
